"""
Django settings for surveymonkeyapp project.


Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '($g%68la(r_u!0i9h^=cv^e(3$2tj^tp_#%s$mwu7@3vhxzq%o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
SURVEYMONKEY_OUTH_URL = "https://api.surveymonkey.com/oauth/authorize/"
SURVEYMONKEY_CLIENT_ID = "lkE_cJOzRV6j0B9bPLaJug"
SURVEYMONKEY_CLIENT_SECRET = "65085943951230993449921484314018791204"
SURVEYMONKEY_VERIFICATION_TOKEN = "pd45cmph4w8I7hrPUIUPin5-u9vMuWm1PDChgAoHQkTyHndCqtT3224Rcn1582NIqaJNNdIDsByaJOFXojIbXKwFkp35e5yFdhCSHefGfoFgukpxrNsIjVakiSXvxmLk"
SURVEYMONKEY_REDIRECT_URL = "http://56317719.ngrok.io/redirecturl/redirecturl/"

YELLOWANT_OAUTH_URL = "https://www.yellowant.com/api/oauth2/authorize/"
YELLOWANT_CLIENT_ID = "3oMAtrDLNeCqNeRS3qclc4TUGo8PnWGZojUyeFw5"
YELLOWANT_CLIENT_SECRET = "yvWK2qrng9jGrMNQIfzgglxFGijwoiW7AEIw0LTyXyjbFuof2iwRRExbYnB3IjrTZTUlnXD3NO02UCFdbb4l7kDSdVO3lT6ne4aPL4RyzQ8iohB8NUSki6t2hQkEmWC1"
YELLOWANT_VERIFICATION_TOKEN = "Ce3dZYWO2cnXT8PI0ney1mSNz4QOwPr8HqVOjNORqBJvFz9OiRYdmsmiPvjLoXhuUdJ6CiHU909jJoLcjeOr2zL9RQ8nIWGVzM1ZEig3ySTRIWpLu4Z2CBU1Z1VJIoaw"
YELLOWANT_REDIRECT_URL = "http://56317719.ngrok.io/redirecturl/yellowantredirecturl/"
# Application definition

SM_API_BASE = "https://api.surveymonkey.com"
USER_INFO_ENDPOINT = "/v3/users/me"
VIEW_CONTACTLISTS = "/v3/contact_lists"
VIEW_SURVEY = "/v3/surveys"
VIEW_WEBHOOKS = "/v3/webhooks"
SURVEY_CATEGORY = "/v3/survey_categories"
SURVEY_TEMPLATES = "/v3/survey_templates"
USER_WORKGROUP_ENDPOINT = "/v3/users/user_id=%s/workgroups"


INSTALLED_APPS = [
    'django.contrib.admin',
    'web.apps.WebConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'records.apps.RecordsConfig',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'surveymonkeyapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'surveymonkeyapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'surveymonkey',
        'USER': 'root',
        'PASSWORD': 'khatri@19',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
