# Generated by Django 2.0.5 on 2018-05-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20180506_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyMonkeyUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SurveyMonkey_token', models.CharField(max_length=100)),
            ],
        ),
    ]
