# Generated by Django 2.0.5 on 2018-05-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_surveymonkeyusertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymonkeyusertoken',
            name='SurveyMonkey_token',
            field=models.TextField(max_length=2000),
        ),
    ]
