# Generated by Django 2.0.5 on 2018-05-07 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0004_auto_20180507_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRedirectState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='YellowAntRedirectState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=512)),
            ],
        ),
        migrations.RemoveField(
            model_name='surveymonkeyusertoken',
            name='SurveyMonkey_token',
        ),
        migrations.AddField(
            model_name='surveymonkeyusertoken',
            name='surveymonkey_access_token',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveymonkeyusertoken',
            name='user_integration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.YellowUserToken'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yellowusertoken',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yellowantredirectstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.YellowUserToken'),
        ),
        migrations.AddField(
            model_name='appredirectstate',
            name='user_integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.YellowUserToken'),
        ),
    ]
