# Generated by Django 2.0.5 on 2018-05-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_contactlistsdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactListsDetails',
        ),
    ]
