# Generated by Django 2.0.5 on 2018-05-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_contactlistsdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactListsDetails',
            new_name='listsDetails',
        ),
    ]
