# Generated by Django 2.0.5 on 2018-05-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_auto_20180508_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='listsDetails',
            new_name='ContactListsDetails',
        ),
    ]
