# Generated by Django 2.0.5 on 2018-05-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_contactlistsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlistsdetails',
            name='user_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
