# Generated by Django 2.0.5 on 2018-05-10 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_auto_20180508_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactListsDetails',
        ),
        migrations.AddField(
            model_name='yellowusertoken',
            name='webhook_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='yellowusertoken',
            name='webhook_last_updated',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
