# Generated by Django 2.0.5 on 2018-05-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_auto_20180516_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymonkeyusertoken',
            name='surveymonkey_access_token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='surveymonkeyusertoken',
            unique_together=set(),
        ),
    ]
