# Generated by Django 2.0.5 on 2018-05-06 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserToken',
            new_name='YellowUserToken',
        ),
    ]
