# Generated by Django 2.0.5 on 2018-05-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_auto_20180508_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactListsDetails',
        ),
    ]
