# Generated by Django 2.0.5 on 2018-05-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_auto_20180508_1651'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactlistsdetails',
            unique_together=set(),
        ),
    ]
