# Generated by Django 2.0.5 on 2018-05-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_auto_20180510_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='yellowusertoken',
            name='yellowant_integration_invoke_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
