# Generated by Django 2.0.5 on 2018-05-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_yellowusertoken_yellowant_integration_invoke_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveymonkeyusertoken',
            unique_together={('user_integration', 'surveymonkey_access_token')},
        ),
    ]
