# Generated by Django 2.0.5 on 2018-05-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0024_auto_20180516_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveymonkeyusertoken',
            name='surveymonkey_access_token',
            field=models.CharField(max_length=501),
        ),
        migrations.AlterUniqueTogether(
            name='surveymonkeyusertoken',
            unique_together={('user_integration', 'surveymonkey_access_token')},
        ),
    ]
